package front;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author nicolashefty
 */
import javax.swing.JOptionPane;
import objects.*;

public class Metodo extends javax.swing.JFrame {

    Controller controller;

    /**
     * Creates new form Menu
     */
    public Metodo(Controller cont) {
        controller = cont;
        initComponents();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accept_btn = new javax.swing.JButton();
        clean_btn = new javax.swing.JButton();
        close_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        a_txt = new javax.swing.JTextField();
        b_txt = new javax.swing.JTextField();
        m_txt = new javax.swing.JTextField();
        seed_txt = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        txt_int_inicial = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        accept_btn.setText("Comenzar");
        accept_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accept_btnActionPerformed(evt);
            }
        });

        clean_btn.setText("Limpiar");
        clean_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_btnActionPerformed(evt);
            }
        });

        close_btn.setText("Salir");
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese los valores:");

        jLabel2.setText("a:");

        jLabel3.setText("b:");

        jLabel4.setText("m:");

        jLabel5.setText("Xo:");

        a_txt.setText("13");
        a_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_txtActionPerformed(evt);
            }
        });

        b_txt.setText("17");

        m_txt.setText("53");

        seed_txt.setText("4");

        back_btn.setText("Volver");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        txt_int_inicial.setText("100");
        txt_int_inicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_int_inicialActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad a generar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(accept_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(back_btn)
                                    .addComponent(clean_btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(m_txt)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seed_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 124, Short.MAX_VALUE))
                            .addComponent(a_txt)
                            .addComponent(b_txt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(close_btn)
                            .addComponent(jLabel1))))
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_int_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(a_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(clean_btn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seed_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(accept_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_int_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(30, 30, 30)
                .addComponent(close_btn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accept_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accept_btnActionPerformed
        // TODO add your handling code here:
        if ((!a_txt.getText().equals("") && Integer.parseInt(a_txt.getText()) >= 0 && Integer.parseInt(a_txt.getText()) <= 9999) && (!b_txt.getText().equals("") && Integer.parseInt(b_txt.getText()) >= 0 && Integer.parseInt(b_txt.getText()) <= 9999) && (!m_txt.getText().equals("") && Integer.parseInt(m_txt.getText()) >= 0 && Integer.parseInt(m_txt.getText()) <= 9999) && (!seed_txt.getText().equals("") && Integer.parseInt(seed_txt.getText()) >= 0 && Integer.parseInt(seed_txt.getText()) <= 9999)) {
            int intervalo = 1;
            if (txt_int_inicial.getText() != null && !txt_int_inicial.getText().isEmpty() && Integer.parseInt(txt_int_inicial.getText()) >= 1)
            {
                intervalo = Integer.parseInt(txt_int_inicial.getText());
            }
            controller.calculate(Integer.parseInt(a_txt.getText()), Integer.parseInt(b_txt.getText()), Integer.parseInt(m_txt.getText()), Integer.parseInt(seed_txt.getText()), intervalo);
        } else {
            JOptionPane.showMessageDialog(null, "Error en los valores", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_accept_btnActionPerformed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_close_btnActionPerformed

    private void a_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_a_txtActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        enableFields();
        clearFields();
        a_txt.setEnabled(true);
        b_txt.setEnabled(true);
        controller.showMenu();
    }//GEN-LAST:event_back_btnActionPerformed

    private void clean_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_btnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clean_btnActionPerformed

    private void txt_int_inicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_int_inicialActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_int_inicialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_txt;
    private javax.swing.JButton accept_btn;
    private javax.swing.JTextField b_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton clean_btn;
    private javax.swing.JButton close_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField m_txt;
    private javax.swing.JTextField seed_txt;
    private javax.swing.JTextField txt_int_inicial;
    // End of variables declaration//GEN-END:variables

    public void setMultiplicativoOnFrame() {
        b_txt.setText("0");
        b_txt.setEnabled(false);
    }

    public void setMethodType(String metodo) {
        if (metodo == "multiplicativo") {
            setMultiplicativoOnFrame();
        }
    }

    public void clearFields() {
        a_txt.setText("");
        if (b_txt.isEnabled()) {
            b_txt.setText("");
        }
        m_txt.setText("");
        seed_txt.setText("");
        txt_int_inicial.setText("");
    }

    public void enableFields() {
        b_txt.setEnabled(true);
    }
}
