package front;

import front.exponencial.*;
import front.poisson.*;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;
import objects.Controller;

/**
 *
 * @author federico
 */
public class GeneratorTable extends javax.swing.JFrame {

    Controller controller;
    String distribucion;
    float[] valores;
    String[] datos;
    
    public GeneratorTable(Controller cont, float[] vec, String distribucion, String[] datos) {
        controller = cont;
        initComponents();
        
        setTitle("Distribución "+distribucion);
        this.distribucion = distribucion;
        
        this.valores = vec;
        this.datos = datos;
        
        DecimalFormat in = new DecimalFormat("0.00");
        DecimalFormat aleat = new DecimalFormat("0.0000");
        DecimalFormat c = new DecimalFormat("0.000");
        
        DefaultTableModel tm = (DefaultTableModel) tabla_valoresA.getModel();
        for (int i = 0; i < vec.length; i++) {
            tm.addRow(new Object[]{i+1 , aleat.format(vec[i])});
        }
        txt_media.setText(""+datos[1]);
        txt_cantNum.setText(""+datos[0]);
        if(controller.getTipo() == Controller.NORMAL){
            txt_desviacion.setText(""+datos[2]);
        }
        
        acomodarADistribucion();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_valoresA = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_media = new javax.swing.JTextField();
        _lblDesviacion = new javax.swing.JLabel();
        txt_desviacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb_intervalo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btn_ejecutar = new javax.swing.JButton();
        btn_volver = new javax.swing.JButton();
        lbl_distribucion = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_cantNum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_valoresA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Generacion", "Número aleatorio"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla_valoresA);

        jLabel1.setText("Media");

        txt_media.setEditable(false);

        _lblDesviacion.setText("Desviación estándar");

        txt_desviacion.setEditable(false);

        jLabel3.setText("Ejecutar prueba de chi cuadrado");

        cmb_intervalo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "10", "20" }));

        jLabel4.setText("Cantidad de intervalos");

        btn_ejecutar.setText("Ejecutar prueba");

        btn_volver.setText("Volver");
        btn_volver.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btn_volverActionPerformed(evt);
            }
        });

        lbl_distribucion.setText("Números aleatorios de distribución");

        jLabel6.setText("Cantidad de numeros");

        txt_cantNum.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_distribucion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ejecutar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_volver))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_media, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(_lblDesviacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_desviacion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_cantNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbl_distribucion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_lblDesviacion)
                    .addComponent(txt_desviacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_cantNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_intervalo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btn_ejecutar)
                    .addComponent(btn_volver))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btn_volverActionPerformed
    {//GEN-HEADEREND:event_btn_volverActionPerformed
        this.dispose();
        controller.showMenu();
    }//GEN-LAST:event_btn_volverActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _lblDesviacion;
    private javax.swing.JButton btn_ejecutar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JComboBox<String> cmb_intervalo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_distribucion;
    private javax.swing.JTable tabla_valoresA;
    private javax.swing.JTextField txt_cantNum;
    private javax.swing.JTextField txt_desviacion;
    private javax.swing.JTextField txt_media;
    // End of variables declaration//GEN-END:variables

    private void acomodarADistribucion()
    {
        switch (distribucion)
        {
            case Controller.EXPONENCIAL:
            {
                txt_desviacion.setVisible(false);
                _lblDesviacion.setVisible(false);
                
                btn_ejecutar.addActionListener((ae) -> 
                {
                    new ExponencialTestTable(this, controller, valores, datos,
                            Integer.parseInt((String) cmb_intervalo.getSelectedItem())).setVisible(true);
                });
                break;
            }
            case Controller.NORMAL:
            {
                btn_ejecutar.addActionListener((ae) ->
                {
                    new NormalTestTable(this, controller, valores, datos, 
                            Integer.parseInt((String) cmb_intervalo.getSelectedItem())).setVisible(true);
                });
                break;
            }
            case Controller.POISSON:
            {
                btn_ejecutar.addActionListener((ae) ->
                {
                    new PoissonTestTable(this, controller, valores, datos,
                                         Integer.parseInt((String) cmb_intervalo.getSelectedItem())).setVisible(true);
                });
                break;
            }
        }
    }
}
