/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.tablas;

import java.time.LocalTime;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import logica.gestion.Simulador;

/**
 *
 * @author heftyn
 */
public class VentanaColas extends javax.swing.JFrame {

    /**
     * Creates new form VentanaColas
     */
    public VentanaColas(int diaInicio, int diaFin) {
                initComponents();
                Runnable thread1 = new Runnable() {
                    @Override
                    public void run() {
                        new Simulador(LocalTime.NOON, (DefaultTableModel)tbl_politica_principal.getModel(), diaInicio, diaFin);
                    }
                };
                thread1.run();
                Runnable thread2 = new Runnable() {
                    @Override
                    public void run() {
                        new Simulador(LocalTime.of(5,0,0), (DefaultTableModel)tbl_politica_alternativa.getModel(), diaInicio, diaFin);
                    }
                };
                thread2.run();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vector_estado = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_politica_principal = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_politica_alternativa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        vector_estado.setBorder(javax.swing.BorderFactory.createTitledBorder("Vector de estado"));

        tbl_politica_principal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbl_politica_principal);

        vector_estado.addTab("Politica principal", jScrollPane2);

        tbl_politica_alternativa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tbl_politica_alternativa);

        vector_estado.addTab("Politica alternativa", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vector_estado, javax.swing.GroupLayout.DEFAULT_SIZE, 1143, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vector_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbl_politica_alternativa;
    private javax.swing.JTable tbl_politica_principal;
    private javax.swing.JTabbedPane vector_estado;
    // End of variables declaration//GEN-END:variables
}
